#!/usr/bin/env python3
"""生成 frontend/src/i18n.ts 的 zhKeys + en 字典（I18N2 轮）。

单一事实来源：本文件的 EN 映射（key=中文原文，value=自然英文）。
用法：python3 .audit/en_dict_gen.py > frontend/src/i18n.ts（由主 agent 落盘）。
"""
import json
import sys

EN = {
    # ===== 通用动作 =====
    '保存': 'Save',
    '取消': 'Cancel',
    '删除': 'Delete',
    '确认': 'Confirm',
    '返回': 'Back',
    '重试': 'Retry',
    '刷新重试': 'Refresh and retry',
    '加载中…': 'Loading…',
    '加载失败': 'Failed to load',
    '加载失败，请稍后重试': 'Failed to load, please try again later',
    '操作失败': 'Something went wrong',
    '操作失败，请重试': 'Operation failed, please retry',
    '提交中…': 'Submitting…',
    '保存中…': 'Saving…',
    '保存修改': 'Save changes',
    '保存资料': 'Save profile',
    '保存偏好': 'Save preferences',
    '保存失败': 'Failed to save',
    '上一步': 'Back',
    '下一步': 'Next',
    '确认删除': 'Confirm delete',
    '删除中…': 'Deleting…',
    '删除失败': 'Failed to delete',
    '、': ', ',
    '信息': 'Info',
    # ===== 网络/操作错误（Toast 公共文案）=====
    '网络连接失败，请检查网络后重试': 'Network error, please check your connection and retry',
    '请求超时，请稍后重试': 'Request timed out, please try again later',
    '请求已取消': 'Request cancelled',
    '请求失败': 'Request failed',
    '上传失败': 'Upload failed',
    '服务响应异常 ({status})': 'Server responded with an error ({status})',
    # ===== 认证 =====
    '登录': 'Log in',
    '注册': 'Sign up',
    '退出': 'Log out',
    '登录中…': 'Logging in…',
    '注册中…': 'Signing up…',
    '用户名': 'Username',
    '密码': 'Password',
    '邮箱': 'Email',
    '确认密码': 'Confirm password',
    '显示密码': 'Show password',
    '隐藏密码': 'Hide password',
    '忘记密码？': 'Forgot password?',
    '请输入用户名和密码': 'Please enter your username and password',
    '请输入用户名或邮箱': 'Please enter your username or email',
    '登录失败，请稍后重试': 'Login failed, please try again later',
    '注册失败，请稍后重试': 'Sign-up failed, please try again later',
    '还没有账号？': "Don't have an account?",
    '立即注册': 'Sign up now',
    '已有账号？': 'Already have an account?',
    '立即登录': 'Log in now',
    '请填写所有字段': 'Please fill in all fields',
    '两次输入的密码不一致': 'The two passwords do not match',
    '两次输入的新密码不一致': 'The two new passwords do not match',
    '至少 2 个字符': 'At least 2 characters',
    '至少 6 位，需包含字母和数字': 'At least 6 characters, with letters and numbers',
    '至少 6 位，含字母和数字': 'At least 6 characters, with letters and numbers',
    '用于登录和找回密码': 'Used to log in and recover your password',
    '加入礼物互赠的乐趣': 'Join the fun of gift exchange',
    '密码不能与用户名相同': 'Password cannot be the same as your username',
    '新密码不能与用户名相同': 'New password cannot be the same as your username',
    '新密码需至少 6 位，包含字母和数字': 'New password needs at least 6 characters, with letters and numbers',
    '互送礼物': 'Gift Exchange',
    '和朋友们交换惊喜': 'Exchange surprises with friends',
    # ===== Header / 通知 =====
    '主导航': 'Main navigation',
    '创建': 'Create',
    '通知': 'Notifications',
    '通知面板': 'Notifications panel',
    '全部已读': 'Mark all as read',
    '清空已读': 'Clear read',
    '暂无通知': 'No notifications',
    '标记已读：{title}': 'Mark as read: {title}',
    '查看活动 ↗': 'View event ↗',
    '个人资料': 'Profile',
    '我的活动': 'My events',
    # ===== 登录/注册页 =====
    '找回密码': 'Recover password',
    '用户名或邮箱': 'Username or email',
    '输入注册时使用的用户名或邮箱': 'Enter the username or email you signed up with',
    '6 位重置码': '6-digit reset code',
    '新密码': 'New password',
    '确认新密码': 'Confirm new password',
    '获取重置码': 'Get reset code',
    '重置密码': 'Reset password',
    '生成中…': 'Generating…',
    '重置中…': 'Resetting…',
    '想起来了？': 'Remember your password?',
    '返回登录': 'Back to login',
    '获取重置码失败，请稍后重试': 'Failed to get the reset code, please try again later',
    '密码重置成功，请用新密码登录': 'Password reset successful — log in with your new password',
    '重置失败，请稍后重试': 'Reset failed, please try again later',
    '重置码已生成：': 'Reset code generated: ',
    '演示模式直接显示，生产环境将通过邮件发送；请在 15 分钟内完成重置。': 'Shown here in demo mode; production sends it by email. Complete the reset within 15 minutes.',
    # ===== 活动列表页 =====
    '我创建的': 'Created by me',
    '我参与的': 'Joined',
    '发现活动': 'Discover',
    '已归档': 'Archived',
    '搜索': 'Search',
    '搜索活动': 'Search events',
    '搜索活动名称 / 邀请码': 'Search event name / invite code',
    '{count} 人': '{count}',
    '你还没有创建活动': 'You haven\'t created any events yet',
    '你还没有参与活动': 'You haven\'t joined any events yet',
    '没有已归档的活动': 'No archived events',
    '没有找到活动': 'No events found',
    '换个关键词试试': 'Try a different keyword',
    '还没有公开活动，发起一个让大家一起玩吧': 'No public events yet — start one and invite your friends',
    '发起一个互送礼物活动，邀请朋友一起玩 🎁': 'Start a gift exchange and invite friends to join 🎁',
    '创建公开活动': 'Create a public event',
    '创建第一个活动': 'Create your first event',
    '朋友分享了邀请码？输入后即可加入': 'Got an invite code from a friend? Enter it to join',
    '用邀请码加入': 'Join with invite code',
    '输入朋友分享的 6 位邀请码，即可进入活动': 'Enter the 6-digit invite code a friend shared to join the event',
    '邀请码': 'Invite code',
    '例如：ABC123': 'e.g. ABC123',
    '请输入邀请码': 'Please enter the invite code',
    '加入': 'Join',
    '检测到剪贴板邀请码 {code}，已为你填入': 'Invite code {code} found on clipboard — filled in for you',
    '活动已恢复': 'Event restored',
    '恢复失败': 'Failed to restore',
    '恢复中…': 'Restoring…',
    '恢复': 'Restore',
    '下拉刷新': 'Pull to refresh',
    '松开刷新': 'Release to refresh',
    '刷新中…': 'Refreshing…',
    '你好，{name}': 'Hi, {name}',
    '{count} 人参与': 'Participants: {count}',
    '报名 {deadline}': 'Sign-up {deadline}',
    '报名中': 'Sign-ups open',
    '已抽签': 'Drawn',
    '创建活动': 'Create event',
    # ===== 创建活动页 =====
    '从模板创建': 'Start from a template',
    '活动名称 *': 'Event name *',
    '例如：圣诞礼物互赠': 'e.g. Christmas gift exchange',
    '活动说明': 'Description',
    '写点规则或想说的话（选填）': 'Add rules or a note (optional)',
    '预算上限（元）': 'Budget cap (¥)',
    '给参与者一个送礼金额参考': 'Gives participants a spending guideline',
    '报名截止日期': 'Sign-up deadline',
    '选填，截止后由你手动抽签': 'Optional — draw manually after it passes',
    '人数上限': 'Max participants',
    '不限': 'No limit',
    '人数上限至少为 2 人': 'Max participants must be at least 2',
    '人数上限不能超过 999': 'Max participants cannot exceed 999',
    '成员名单（每行一个用户名）': 'Member list (one username per line)',
    '来自上期活动，不会自动加入新活动，方便你复制邀请名单': 'Carried over from the previous event; not auto-joined, just handy for copying invite lists',
    '📋 复制名单': '📋 Copy list',
    '每行一对，用逗号分隔用户名\n例如：小明, 小红': 'One pair per line, usernames separated by commas\\nExample: xiaoming, xiaohong',
    '第 {n} 行格式应为「用户名1, 用户名2」': 'Line {n} should be "username1, username2"',
    '谁可以看到这个活动': 'Who can see this event',
    '公开（所有人可见）': 'Public (everyone can see)',
    '私密（仅凭链接）': 'Private (link only)',
    '抽签结果可见性': 'Draw result visibility',
    '仅个人可见（推荐）': 'Visible only to each person (recommended)',
    '所有人可见': 'Visible to everyone',
    '仅个人可见时，每个人只能看到自己送谁': 'When private, each person only sees who they are giving to',
    '互避规则（选填）': 'Avoidance rules (optional)',
    '互避 = 这两人不会互送礼物（如情侣/夫妻）': 'Avoid = these two won\'t gift each other (e.g. couples)',
    '规则按用户名填写；从「再开一局」带入成员名单时提交即生效，抽签时自动避开这些配对': 'Enter usernames; takes effect on submit when carried from "Play again", and the draw will skip these pairs',
    '互避规则需与成员用户名对应。请使用「再开一局」带入成员名单后配置，或创建活动邀请成员后再配置': 'Avoidance rules must match member usernames. Use "Play again" to bring in the member list, or configure after inviting members',
    '互避规则过多可能导致无法抽签（计划 {expected} 人、已配置 {count} 组），请减少规则数量': 'Too many avoidance rules may make the draw impossible ({expected} people planned, {count} pairs configured). Please reduce the number of rules',
    '无法识别的成员用户名：{names}，请与名单保持一致': 'Unrecognized member username(s): {names} — keep the list consistent',
    '已应用「{name}」模板，可再调整': 'Template "{name}" applied — you can tweak it',
    '封面图片': 'Cover image',
    '选填，支持 png / jpg / jpeg / gif / webp，最大 5MB': 'Optional, supports png / jpg / jpeg / gif / webp, up to 5MB',
    '请填写活动名称': 'Please enter the event name',
    '预算不能为负数或无效数字': 'Budget cannot be negative or invalid',
    '报名截止日期格式无效': 'Invalid sign-up deadline format',
    '报名截止日期不能早于现在': 'Sign-up deadline cannot be in the past',
    '活动创建成功！': 'Event created!',
    '创建失败，请稍后重试': 'Failed to create, please try again later',
    '成员名单已复制': 'Member list copied',
    '复制失败，请手动选择复制': 'Copy failed, please copy manually',
    '创建中…': 'Creating…',
    # ===== 模板预设 =====
    '圣诞交换': 'Christmas Exchange',
    '圣诞礼物交换': 'Christmas Gift Exchange',
    '今年圣诞，我们把心意藏在礼物里 🎁': 'This Christmas, we hide our wishes inside gifts 🎁',
    '12月20日': 'Dec 20',
    '生日惊喜': 'Birthday Surprise',
    '生日惊喜派对': 'Birthday Surprise Party',
    '给寿星的礼物盲盒，大家一起宠 TA 🎂': 'A gift box for the birthday star — everyone spoils them 🎂',
    '生日前一周': 'One week before the birthday',
    '新年聚会': 'New Year Gathering',
    '新年礼物互赠': 'New Year Gift Exchange',
    '新年新气象，互相送份小确幸 🧧': 'A fresh new year — exchange little joys 🧧',
    '元旦前三天': 'Three days before New Year',
    # ===== 活动详情页 =====
    '活动详情': 'Event details',
    '活动不存在': 'Event not found',
    '加载活动失败，请稍后重试': 'Failed to load the event, please try again later',
    '活动不存在或已失效，链接可能有误': 'This event doesn\'t exist or has expired — the link may be wrong',
    '活动封面': 'Event cover',
    '预算': 'Budget',
    '参与人数': 'Participants',
    '报名截止': 'Sign-up deadline',
    '活动说明': 'Description',
    '这个活动已经开始啦，登录后看看大家交换了什么礼物吧': 'This event has started — log in to see what everyone exchanged',
    '登录后加入': 'Log in to join',
    '没有账号？立即注册': 'No account? Sign up now',
    '加入这个活动': 'Join this event',
    '公开活动': 'Public event',
    '私密活动': 'Private event',
    '分享邀请码或复制邀请链接，把朋友拉进来一起玩': 'Share the invite code or copy the invite link to bring friends in',
    '点击复制邀请码': 'Click to copy invite code',
    '📋 复制邀请链接': '📋 Copy invite link',
    '🖼️ 邀请海报': '🖼️ Invite poster',
    '邀请链接已复制！': 'Invite link copied!',
    '邀请码 {sc} 已复制！': 'Invite code {sc} copied!',
    '邀请码：{sc}': 'Invite code: {sc}',
    '邀请链接：{inviteUrl}': 'Invite link: {inviteUrl}',
    '朋友邀请你参加「{title}」🎁 登录后即可查看详情并加入': 'A friend invited you to "{title}" 🎁 Log in to view and join',
    '活动流程': 'Event flow',
    '招募中：分享邀请码让朋友加入（当前 {count} 人）': 'Recruiting: share the invite code to bring friends in ({count} so far)',
    '等组织者邀请更多朋友后，就可以开始抽签啦': 'Once the organizer invites more friends, the draw can begin',
    '至少 2 人才能抽签': 'At least 2 people are needed to draw',
    '开始抽签': 'Start the draw',
    '抽签中…': 'Drawing…',
    '确认抽签': 'Confirm draw',
    '确认抽签？': 'Start the draw?',
    '抽签完成！': 'Draw complete!',
    '抽签失败': 'Draw failed',
    '当前 {count} 人参与。抽签后不可撤销，每个人将获得一个送礼对象。': 'Current participants: {count}. The draw is irreversible — everyone gets a gift recipient.',
    '提示：{count} 人未填完整收件信息，抽签后对方可能收不到礼物。': 'Note: {count} haven\'t completed their shipping info; after the draw they may not receive gifts',
    '⚠️ 已配置 {count} 组互避规则，抽签时会避开这些配对': '⚠️ {count} avoidance rule(s) configured; the draw will avoid these pairs',
    '⚠️ 已配置 {count} 组互避规则，重新抽签会继续避开这些配对': '⚠️ {count} avoidance rule(s) configured; a redraw will keep avoiding these pairs',
    '抽签后，送你礼物的人会看到这些信息来寄礼物': 'After the draw, your gift giver sees this info to send your gift',
    '你已加入，等待组织者抽签': 'You\'ve joined — waiting for the organizer to draw',
    '你是组织者，活动已创建，无需加入': 'You\'re the organizer — the event is already created, no need to join',
    '报名截止前加入，即可参与抽签': 'Join before the deadline to take part in the draw',
    '报名已截止，点击「开始抽签」': 'Sign-up closed — click "Start the draw"',
    '报名已截止，等待组织者抽签': 'Sign-up closed — waiting for the organizer to draw',
    '加入活动': 'Join event',
    '确认加入': 'Confirm join',
    '加入成功！': 'Joined!',
    '加入失败': 'Failed to join',
    '请填写收件人姓名、电话和地址（必填）': 'Please fill in recipient name, phone and address (required)',
    '收件信息': 'Shipping info',
    '真实姓名': 'Full name',
    '联系电话 *': 'Phone *',
    '收件人姓名 *': 'Recipient name *',
    '省市区 + 详细地址': 'Region + full address',
    '收件地址 *': 'Address *',
    '收件人：': 'Recipient: ',
    '电话：': 'Phone: ',
    '地址：': 'Address: ',
    '📝待填信息': '📝 Info needed',
    '✅已就绪': '✅ Ready',
    '📦已发货': '📦 Shipped',
    '✨已晒图': '✨ Posted',
    '🎯 我的送礼任务': '🎯 My gifting task',
    '我要送给 {name}': 'I\'m giving to {name}',
    '💰 预算参考：{budget}': '💰 Budget reference: {budget}',
    '❤️ 喜欢：{likes}': '❤️ Likes: {likes}',
    '🚫 不喜欢：{dislikes}': '🚫 Dislikes: {dislikes}',
    '📏 尺码：{size}': '📏 Size: {size}',
    '🎨 颜色：{color}': '🎨 Color: {color}',
    '📝 备注：{notes}': '📝 Notes: {notes}',
    '🎁 心愿链接：': '🎁 Wish links: ',
    '💬 悄悄话：{note}': '💬 Secret note: {note}',
    '💬 悄悄话：收礼人晒图后揭晓 ✨': '💬 Secret note: revealed after the recipient posts ✨',
    '去完成你的送礼任务，收到礼物记得晒图': 'Go complete your gifting task — and don\'t forget to post your gift',
    '看看大家都收到了什么礼物，给喜欢的点赞！': 'See what everyone received and like your favorites!',
    '我喜欢的礼物': 'Gifts I like',
    '我不想要的': 'Things I don\'t want',
    '心愿单': 'Wishlist',
    '心愿{i} ↗': 'Wish {i} ↗',
    '心愿链接（选填，最多 3 个）': 'Wish links (optional, up to 3)',
    '评价（选填）': 'Review (optional)',
    '收到礼物想说点什么？': 'What do you want to say about the gift?',
    '附一句悄悄话（选填）': 'Add a secret note (optional)',
    '附一句悄悄话（选填）💌': 'Add a secret note (optional) 💌',
    '上传照片': 'Upload photo',
    '上传照片（将模糊展示）': 'Upload photo (shown blurred)',
    '照片会以模糊效果展示在礼物墙，其他人点击可查看原图': 'The photo appears blurred on the gift wall; others can click to view the original',
    '晒图形式': 'Post format',
    '📷 公开照片': '📷 Public photo',
    '照片直接展示在礼物墙': 'Shown directly on the gift wall',
    '📝 仅文字': '📝 Text only',
    '不传照片，只写评价也能晒出': 'No photo needed — a review is enough',
    '🌫️ 模糊照片': '🌫️ Blurred photo',
    '照片模糊展示，点击可查看原图': 'Shown blurred; click to view the original',
    '📝 仅文字模式：无需上传照片，写好评价即可晒出': 'Text-only mode: no photo needed, just write a review',
    '晒出礼物 🎉': 'Post the gift 🎉',
    '晒图成功 🎉': 'Posted! 🎉',
    '晒图已删除': 'Post deleted',
    '请先给礼物评分 ⭐': 'Please rate the gift first ⭐',
    '请填写评价内容': 'Please write a review',
    '请上传一张照片（或选择「仅文字」模式）': 'Please upload a photo (or choose "Text only" mode)',
    '评分 *': 'Rating *',
    '评分 {rating}/5': 'Rating {rating}/5',
    '{n} 星': '{n} stars',
    '删除晒图？': 'Delete this post?',
    '删除晒图': 'Delete post',
    '修改晒图': 'Edit post',
    '删除后你的评分、评价和照片会从礼物墙移除，礼物卡片将恢复未揭晓状态。此操作不可撤销。': 'Your rating, review and photo will be removed from the wall and the card returns to hidden. This cannot be undone.',
    '🎁 我收到的礼物': '🎁 The gift I received',
    '来自 {giverName} 的礼物 —— 晒出后，礼物墙就离解锁更近一步 🎀': 'A gift from {giverName} — post it to bring the gift wall one step closer to unlocking 🎀',
    '来自 {giverName} 的礼物，你已晒出（{privacy}）': 'Gift from {giverName} — you\'ve posted it ({privacy})',
    '模糊照片，点击查看原图': 'Blurred photo — click to view original',
    '礼物照片': 'Gift photo',
    '👁 点击隐藏原图': '👁 Click to hide original',
    '🌫️ 模糊照片 · 点击查看原图': '🌫️ Blurred · click to view',
    '礼物墙': 'Gift Wall',
    '🎁 礼物墙': '🎁 Gift Wall',
    '🎁 礼物照片': '🎁 Gift photo',
    '送礼进度': 'Gifting progress',
    '待购买': 'To buy',
    '已发货': 'Shipped',
    '已签收': 'Delivered',
    '已晒图': 'Posted',
    '已送达': 'Delivered',
    '未发货': 'Not shipped',
    '已发货{check}': 'Shipped{check}',
    '🚚 发货进度': '🚚 Shipping progress',
    '🔄 刷新物流信息': '🔄 Refresh tracking',
    '物流查询仍失败，请稍后再试': 'Tracking lookup still failed, please try again later',
    '物流信息已刷新': 'Tracking refreshed',
    '刷新失败，请稍后重试': 'Refresh failed, please try again later',
    '修改物流信息': 'Edit shipping info',
    '填写快递单号': 'Enter tracking number',
    '快递公司（选填）': 'Carrier (optional)',
    '快递单号 *': 'Tracking number *',
    '快递单号（必填）': 'Tracking number (required)',
    '单号：': 'Tracking no.: ',
    '（{carrier}）': ' ({carrier})',
    '请填写快递单号': 'Please enter the tracking number',
    '发货信息已保存 🚚': 'Shipping info saved 🚚',
    '确认发货': 'Confirm shipment',
    '备注（选填）': 'Note (optional)',
    '已收货': 'Received',
    '已晒': 'Posted',
    '催办未完成成员': 'Nudge incomplete members',
    '催办中…': 'Nudging…',
    '催办失败': 'Failed to nudge',
    '已提醒 {reminded} 人': 'Reminded {reminded}',
    '重新抽签': 'Redraw',
    '重新抽签？': 'Redraw?',
    '确认重新抽签': 'Confirm redraw',
    '重抽中…': 'Redrawing…',
    '重新抽签失败': 'Redraw failed',
    '已重新抽签！请查看新的任务': 'Redrawn! Check your new task',
    '所有成员的任务将重置，已发货/已晒图的数据会清空，此操作不可撤销。': 'All tasks reset; shipped/posted data is cleared. This cannot be undone.',
    '归档活动': 'Archive event',
    '归档活动？': 'Archive this event?',
    '确认归档': 'Confirm archive',
    '归档中…': 'Archiving…',
    '归档失败': 'Failed to archive',
    '活动已归档': 'Event archived',
    '归档后活动将从「我创建的」列表隐藏，进入「已归档」。详情页、礼物墙、管理台数据不受影响，可随时恢复。': 'The event hides from "Created by me" and moves to "Archived". Details, wall and dashboard stay intact and it can be restored anytime.',
    '🔄 重置邀请码': '🔄 Reset invite code',
    '重置邀请码？': 'Reset the invite code?',
    '确认重置': 'Confirm reset',
    '重置失败': 'Failed to reset',
    '邀请码已重置，旧邀请码已失效': 'Invite code reset — the old code no longer works',
    '旧邀请码将立即失效，已转发的旧邀请链接将无法再进入活动，此操作不可撤销。': 'The old code stops working immediately; forwarded links will no longer open the event. This cannot be undone.',
    '我喜欢的礼物': 'Gifts I like',
    '去看看': 'Take a look',
    '回我的活动': 'Back to my events',
    '还没有人加入': 'No one has joined yet',
    '送礼进行中，看看大家的礼物墙': 'Gifting in progress — check out the gift wall',
    '活动已完结，去礼物墙看看大家的分享': 'Event finished — see everyone\'s posts on the gift wall',
    '参与者（{count}）': 'Participants ({count})',
    '招募中': 'Recruiting',
    '已截止待抽签': 'Closed, awaiting draw',
    '送礼进行中': 'Gifting in progress',
    '已完结': 'Finished',
    # ===== 管理台 =====
    '活动管理台': 'Event Dashboard',
    '无法查看管理台': 'Cannot view this dashboard',
    '无权限或活动不存在': 'No permission or the event doesn\'t exist',
    '进度明细': 'Progress details',
    '参与者': 'Participants',
    '发货': 'Shipping',
    '收货': 'Receiving',
    '晒图': 'Posts',
    '待发货': 'To ship',
    '待晒图': 'To post',
    '待抽签': 'Awaiting draw',
    '齐全': 'Complete',
    '缺收件信息': 'Missing shipping info',
    '缺偏好': 'Missing preferences',
    '还没有参与者': 'No participants yet',
    '邀请朋友加入后，这里会显示每个人的进度': 'Invite friends and each person\'s progress shows here',
    '去复制邀请链接': 'Copy invite link',
    '返回活动': 'Back to event',
    '下载 JSON 文件：个人资料、我创建/参与的活动、晒图记录（各截取最近 100 条）': 'Downloads a JSON file: profile, events you created/joined, and gift posts (latest 100 of each)',
    # ===== 礼物墙 =====
    '加载礼物墙失败': 'Failed to load the gift wall',
    '暂无数据': 'No data',
    '还没有人加入活动，礼物墙稍后揭晓 🎁': 'No one has joined yet — the wall will reveal itself later 🎁',
    '礼物墙已解锁，但还没有晒出的礼物 🎁': 'The wall is unlocked, but no gifts posted yet 🎁',
    '还没有人晒出礼物，收到礼物并晒图后，礼物墙就会揭晓 🎀': 'No gifts posted yet — once received and posted, the wall reveals itself 🎀',
    '所有参与者送出礼物并晒图后，礼物墙自动解锁，敬请期待 ✨': 'Once everyone sends and posts their gifts, the wall auto-unlocks. Stay tuned ✨',
    '{posted}/{total} 已送出并晒图，还差 {remaining} 人解锁 🔒': '{posted}/{total} sent and posted — {remaining} more to unlock 🔒',
    '点击揭晓': 'Click to reveal',
    '点击揭晓这份礼物': 'Click to reveal this gift',
    '🎁 礼物照片': '🎁 Gift photo',
    '📝 文字心意': '📝 Text note',
    '仅文字晒图': 'Text-only post',
    '🌫️ 模糊照片 · 点击查看': '🌫️ Blurred · click to view',
    '去晒出你的礼物': 'Post your gift',
    '返回活动晒出第一份礼物': 'Back to the event to post the first gift',
    '🏆 生成高光海报': '🏆 Generate highlight poster',
    '🔁 再开一局': '🔁 Play again',
    '确认再开一局': 'Confirm "Play again"?',
    '用当前活动的标题、预算和说明创建新活动': 'Creates a new event with this event\'s title, budget and description',
    '复制成员名单': 'Copy member list',
    '带入上期成员用户名，方便复制邀请（不会自动加入）': 'Brings in last round\'s member usernames for easy inviting (no auto-join)',
    '互避规则暂不复制，新活动需重新配置': 'Avoidance rules are not copied — configure them in the new event',
    '准备中…': 'Preparing…',
    '已复制 {count} 位成员名单': 'Copied {count} member names',
    '成员名单获取失败，已仅复制活动配置': 'Couldn\'t fetch the member list — copied the event config only',
    # ===== 个人中心 =====
    '常用信息': 'Common info',
    '昵称': 'Nickname',
    '手机号': 'Phone',
    '常用收件人': 'Default recipient',
    '常用地址': 'Default address',
    '礼物偏好': 'Gift preferences',
    '收礼人姓名': 'Recipient name',
    '收礼地址': 'Recipient address',
    '偏好加载失败': 'Failed to load preferences',
    '喜欢什么 / 不喜欢什么 / 尺码颜色等': 'Likes / dislikes / sizes & colors, etc.',
    '保存后，加入新活动时会自动帮你填好收件信息 ✨': 'Saved info auto-fills your shipping details when joining new events ✨',
    '点击更换头像': 'Click to change avatar',
    '点击头像更换 ✏️': 'Click the avatar to change ✏️',
    '更换头像': 'Change avatar',
    '头像': 'Avatar',
    '头像已更新 ✨': 'Avatar updated ✨',
    '头像上传失败': 'Avatar upload failed',
    '请选择图片文件': 'Please choose an image file',
    '图片不能超过 5MB': 'Image cannot exceed 5MB',
    '上传中…': 'Uploading…',
    '上传失败，请稍后重试': 'Upload failed, please try again later',
    '个人资料已保存 ✅': 'Profile saved ✅',
    '通知偏好': 'Notification preferences',
    '截止提醒': 'Deadline reminders',
    '报名截止前 48 小时 / 24 小时提醒组织者及时抽签': 'Reminds the organizer to draw 48h / 24h before the deadline',
    '抽签结果': 'Draw results',
    '抽签完成或重置后，通知所有参与者查看新的送礼任务': 'Notifies everyone after a draw or redraw to check their new task',
    '晒图提醒': 'Post alerts',
    '礼物被晒图评价、礼物墙解锁时通知': 'Notifies when a gift is reviewed or the wall unlocks',
    '催办动态': 'Nudge activity',
    '有人加入活动、礼物发货时通知': 'Notifies when someone joins or a gift ships',
    '关闭后不再接收对应类型的通知（已收通知保留，铃铛里仍可查看）': 'Turn off a type to stop receiving it (existing notifications stay in the bell)',
    '通知偏好已保存 ✅': 'Notification preferences saved ✅',
    '修改密码': 'Change password',
    '当前密码': 'Current password',
    '当前登录密码': 'Your current password',
    '输入当前密码': 'Enter current password',
    '再次输入新密码': 'Re-enter new password',
    '输入密码确认': 'Enter password to confirm',
    '修改中…': 'Changing…',
    '修改失败': 'Failed to change',
    '密码已修改 ✅ 下次登录请使用新密码': 'Password changed ✅ — use the new one next time',
    '数据与账户': 'Data & account',
    '数据导出': 'Export data',
    '导出中…': 'Exporting…',
    '导出失败': 'Failed to export',
    '数据已导出 ✅': 'Data exported ✅',
    '注销账号': 'Deactivate account',
    '注销账号？': 'Deactivate account?',
    '确认注销': 'Confirm deactivate',
    '注销中…': 'Deactivating…',
    '注销失败': 'Failed to deactivate',
    '账号已注销': 'Account deactivated',
    '注销后账号将无法登录，收件地址等个人资料会被清除；活动与礼物墙数据会保留但不再关联你的身份。此操作不可撤销。': 'After deactivation you can\'t log in, and personal data like your address is cleared. Event and gift-wall data stays but is no longer linked to you. This cannot be undone.',
    '注册于 {date}': 'Joined {date}',
    # ===== 海报 =====
    '📣 邀请海报': '📣 Invite poster',
    '🏆 高光海报': '🏆 Highlight poster',
    '邀请海报': 'Invite poster',
    '高光海报': 'Highlight poster',
    '✅ 已下载': '✅ Downloaded',
    '⬇️ 下载海报': '⬇️ Download poster',
    '{label}-{title}.png': '{label}-{title}.png',
    '🎁 互送礼物': '🎁 Gift Exchange',
    '朋友间的心意交换': 'A heartfelt exchange between friends',
    '一次温暖的心意交换': 'A warm exchange of hearts',
    '预算 ¥{budget}': 'Budget ¥{budget}',
    '{participantCount} 人参与': 'Participants: {participantCount}',
    '{totalPosted} 份心意': 'Gifts shared: {totalPosted}',
    '邀请码 {shortCode}': 'Invite code {shortCode}',
    '扫码或输入邀请码加入': 'Scan the code or enter the invite code to join',
    '我们完成了一次礼物交换 🎉': 'We completed a gift exchange 🎉',
    '感谢每一位参与者': 'Thank you to every participant',
    '等你加入，一起交换心意': 'Waiting for you to join the exchange',
    '期待下一次心意交换': 'Looking forward to the next exchange',
    '二维码生成失败': 'Failed to generate the QR code',
    '关闭': 'Close',
    '其他想说的话': 'Anything else you want to say',
    '喜欢的颜色（选填）': 'Favorite colors (optional)',
    '如 M / 42 码': 'e.g. M / size 42',
    '如 莫兰迪色系': 'e.g. Morandi tones',
    '尺码（选填）': 'Size (optional)',
    '我是组织者': "I'm the organizer",
    '淘宝/京东等商品链接，逗号分隔': 'Links from Taobao/JD etc., comma-separated',
    '让送礼的人更懂你（全部选填，但填得越多礼物越合心意 🎁）': 'Help your giver get to know you (all optional — the more you share, the better the gift 🎁)',
    '📋 已从个人资料自动填入，可修改': '📋 Auto-filled from your profile — you can edit',
    '例如：咖啡、书、手作': 'e.g. coffee, books, handmade',
    '例如：香水、毛绒玩具': 'e.g. perfume, plush toys',
    # ===== 图片上传 =====
    '上传图片': 'Upload image',
    '更换图片': 'Change image',
    '图片预览': 'Image preview',
    '仅支持 png / jpg / jpeg / gif / webp 图片': 'Only png / jpg / jpeg / gif / webp images are supported',
    # ===== 错误边界 =====
    '页面出错了': 'Something went wrong',
    '渲染时遇到了一点问题，刷新重试即可': 'A glitch occurred while rendering — refresh and try again',
    # ===== 日期 =====
    '今天截止': 'Ends today',
    '明天截止': 'Ends tomorrow',
    '还剩 {days} 天': '{days} days left',
    '已截止（{date}）': 'Ended ({date})',
}

if __name__ == '__main__':
    keys = json.load(open('/tmp/i18n_keys.json'))
    missing = [k for k in keys if k not in EN]
    if missing:
        print('MISSING EN for:', file=sys.stderr)
        for k in missing:
            print('  ', k, file=sys.stderr)
        sys.exit(1)
    orphans = [k for k in EN if k not in keys]
    if orphans:
        print('ORPHAN EN keys (not used):', file=sys.stderr)
        for k in orphans:
            print('  ', k, file=sys.stderr)
        sys.exit(1)
    print(f'# generated by .audit/en_dict_gen.py — {len(keys)} keys, 100% coverage', file=sys.stderr)
    print('OK')
